# libraries

import os
from snakemake.utils import min_version

min_version("6.4.1")


wildcard_constraints:
    sample="[\da-zA-Z]+_?[\da-zA-Z]*",
    project="[\da-zA-Z]+_?[\da-zA-Z]*",


##### setup report #####
configfile: "config/config.yaml"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://condaforge/mambaforge:22.11.1-4"





include: "rules/common.smk"

include: "rules/prepare_reference.smk"
include: "rules/fusion/align.smk"
include: "rules/fusion/genion.smk"
include: "rules/fusion/longgf.smk"
include: "rules/fusion/jaffal.smk"
include: "rules/fusion/aeron.smk"



##### target rules #####


rule all:
    input:
        get_final_output(),
