reference:
  genome:
  transcriptome:
  annotation:
  transtable:
  knowntable:

threads:
  minimap2: 12

params:
  minimap2_genion: -c -y -x splice -k 12 -w 3 --hard-mask-level -N 100
  minimap2_longgf: -ax splice -uf

misc:
  genion_dup_file_link: ftp://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz

fusion:
  genion: True
  longgf: True
  jaffal: True
