samples: config/samples.tsv

project: pipeline_test

reference:
  genome: resources/Homo_sapiens.GRCh38.dna.primary_assembly.fa
  transcriptome: resources/transcriptome.fa
  #transcriptome: data/hg38_genCode22.fa
  annotation: resources/Homo_sapiens.GRCh38.104.gtf
  transtable: resources/transtable.tab
  #transtable: data/hg38_genCode22.tab
  knowntable: resources/known_fusions.txt

threads:
  minimap2: 24
  vg: 24
  aeron: 24

params:
  minimap2_genion: -c -y -x splice -k 12 -w 3 --hard-mask-level -N 100
  minimap2_longgf: -ax splice -uf
  aeron_genome_alignment: --try-all-seeds --seeds-mxm-length 17 --seeds-mem-count 15 -b 35 --greedy-length

misc:
  genion_dup_file_link: ftp://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz

fusion:
  genion: True
  longgf: True
  jaffal: True
  aeron: False

